name: 'CD'

on:
  push:
    branches: [main]

jobs:
  PushImage:
    name: Build and Push Image to Docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push to Docker Container Registry
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: .
          tags: |
            artiefuzzz/apex:latest